# Generated by Django 5.2.1 on 2025-06-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("user_name", models.CharField(max_length=255, unique=True)),
                ("is_staff", models.BooleanField(blank=True, default=False)),
                ("is_superuser", models.BooleanField(blank=True, default=False)),
                ("is_active", models.BooleanField(blank=True, default=True)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "categories",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Todos",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("is_done", models.IntegerField(blank=True, null=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("priority", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "todos",
                "managed": False,
            },
        ),
    ]
